In [ ]:
import numpy as np

np.random.randint(999, size=(3,100))


array([[724, 307, 124, 607,  43, 453, 684, 601, 668,  93, 331, 641, 919,
        337, 856, 500, 775, 342, 976, 655, 812, 775, 979, 985, 769, 458,
        142,  22,  26, 591, 528, 265, 391, 750, 693, 978, 410,  75, 784,
        232, 771, 924, 379, 551,  83, 721,  39, 972, 835, 352, 138, 970,
         16, 966, 194, 884, 738, 995, 858, 689, 352, 820, 809, 971, 340,
         53, 640, 348, 280, 417, 443,  71, 814, 835, 924, 941, 777, 598,
        546, 482, 997, 324, 120, 480, 796, 729, 569, 427, 989, 928, 810,
        476, 795,  35, 355, 142, 623, 619, 960, 844],
       [824, 291, 172, 727, 359, 507, 273, 397,  53,  89, 195, 265, 406,
        696,  97, 101, 737, 338, 502, 267, 396, 367, 677,  64, 696, 479,
        686, 276,  36, 967, 715, 904, 452, 955, 278, 847,  84, 862, 186,
        792, 820, 441, 916, 417, 370, 986, 610, 218, 849,  52, 251, 742,
         27, 210, 583, 332,  73, 648, 482, 422, 517, 977, 690, 911, 473,
        611, 630, 719, 426, 129, 798, 184, 286, 913, 916, 955, 823, 67

In [ ]:
import numpy as np

import statistics as std

arr1 = np.array([724, 307, 124, 607,  43, 453, 684, 601, 668,  93, 331, 641, 919,
        337, 856, 500, 775, 342, 976, 655, 812, 775, 979, 985, 769, 458,
        142,  22,  26, 591, 528, 265, 391, 750, 693, 978, 410,  75, 784,
        232, 771, 924, 379, 551,  83, 721,  39, 972, 835, 352, 138, 970,
         16, 966, 194, 884, 738, 995, 858, 689, 352, 820, 809, 971, 340,
         53, 640, 348, 280, 417, 443,  71, 814, 835, 924, 941, 777, 598,
        546, 482, 997, 324, 120, 480, 796, 729, 569, 427, 989, 928, 810,
        476, 795,  35, 355, 142, 623, 619, 960, 844])
arr2 = np.array([824, 291, 172, 727, 359, 507, 273, 397,  53,  89, 195, 265, 406,
        696,  97, 101, 737, 338, 502, 267, 396, 367, 677,  64, 696, 479,
        686, 276,  36, 967, 715, 904, 452, 955, 278, 847,  84, 862, 186,
        792, 820, 441, 916, 417, 370, 986, 610, 218, 849,  52, 251, 742,
         27, 210, 583, 332,  73, 648, 482, 422, 517, 977, 690, 911, 473,
        611, 630, 719, 426, 129, 798, 184, 286, 913, 916, 955, 823, 671,
        647, 839, 905, 318, 408,  47, 605, 751, 745, 555, 937, 283, 402,
         97, 620, 977, 153, 439, 905, 859, 657, 502])
arr3 = np.array([560, 230, 931, 911, 399, 544, 114, 825, 244, 204, 856, 523, 287,
        724,  87,  25, 449, 738, 691, 987,   4, 781, 392, 863, 658, 358,
         41, 639, 739, 140, 690, 793, 193, 876, 474, 674, 772, 422, 566,
        641, 472, 605, 392, 421, 284, 764, 948, 408, 125,  96, 671, 966,
        893, 719, 640, 629, 662, 998, 649, 735, 236, 489, 270, 399, 251,
        940, 189, 472, 451, 796, 504, 686, 233, 820, 773, 509, 698, 597,
        943, 547, 263, 752, 253, 733, 364, 430, 823, 112,  85, 129, 633,
         79, 836, 871, 435, 806, 951, 218, 176, 962])

print("Suma", arr1 + arr2 + arr3)
print("Resta", arr1 - arr2 - arr3)
print("Multiplicacion", arr1 * arr2 * arr3)
print("Division", arr1 / arr2 / arr3)

print("Media", np.mean(arr1), np.mean(arr2), np.mean(arr3))
print("Mediana", np.median(arr1), np.median(arr2), np.median(arr3))
print("Desviacion estandar", np.std(arr1), np.std(arr2), np.std(arr3))

Suma [2108  828 1227 2245  801 1504 1071 1823  965  386 1382 1429 1612 1757
 1040  626 1961 1418 2169 1909 1212 1923 2048 1912 2123 1295  869  937
  801 1698 1933 1962 1036 2581 1445 2499 1266 1359 1536 1665 2063 1970
 1687 1389  737 2471 1597 1598 1809  500 1060 2678  936 1895 1417 1845
 1473 2641 1989 1846 1105 2286 1769 2281 1064 1604 1459 1539 1157 1342
 1745  941 1333 2568 2613 2405 2298 1866 2136 1868 2165 1394  781 1260
 1765 1910 2137 1094 2011 1340 1845  652 2251 1883  943 1387 2479 1696
 1793 2308]
Resta [ -660  -214  -979 -1031  -715  -598   297  -621   371  -200  -720  -147
   226 -1083   672   374  -411  -734  -217  -599   412  -373   -90    58
  -585  -379  -585  -893  -749  -516  -877 -1432  -254 -1081   -59  -543
  -446 -1209    32 -1201  -521  -122  -929  -287  -571 -1029 -1519   346
  -139   204  -784  -738  -904    37 -1029   -77     3  -651  -273  -468
  -401  -646  -151  -339  -384 -1498  -179  -843  -597  -508  -859  -799
   295  -898  -765  -523  -744  -670 -1044

In [ ]:
import numpy as np

p = "Palabra"

arr = np.array([[724, 307, 124, 607,  43, 453, 684, 601, 668,  93, 331, 641, 919,
        337, 856, 500, 775, 342, 976, 655, 812, 775, 979, 985, 769, 458,
        142,  22,  26, 591, 528, 265, 391, 750, 693, 978, 410,  75, 784,
        232, 771, 924, 379, 551,  83, 721,  39, 972, 835, 352, 138, 970,
         16, 966, 194, 884, 738, 995, 858, 689, 352, 820, 809, 971, 340,
         53, 640, 348, 280, 417, 443,  71, 814, 835, 924, 941, 777, 598,
        546, 482, 997, 324, 120, 480, 796, 729, 569, 427, 989, 928, 810,
        476, 795,  35, 355, 142, 623, 619, 960, 844],
       [824, 291, 172, 727, 359, 507, 273, 397,  53,  89, 195, 265, 406,
        696,  97, 101, 737, 338, 502, 267, 396, 367, 677,  64, 696, 479,
        686, 276,  36, 967, 715, 904, 452, 955, 278, 847,  84, 862, 186,
        792, 820, 441, 916, 417, 370, 986, 610, 218, 849,  52, 251, 742,
         27, 210, 583, 332,  73, 648, 482, 422, 517, 977, 690, 911, 473,
        611, 630, 719, 426, 129, 798, 184, 286, 913, 916, 955, 823, 671,
        647, 839, 905, 318, 408,  47, 605, 751, 745, 555, 937, 283, 402,
         97, 620, 977, 153, 439, 905, 859, 657, 502],
       [560, 230, 931, 911, 399, 544, 114, 825, 244, 204, 856, 523, 287,
        724,  87,  25, 449, 738, 691, 987,   4, 781, 392, 863, 658, 358,
         41, 639, 739, 140, 690, 793, 193, 876, 474, 674, 772, 422, 566,
        641, 472, 605, 392, 421, 284, 764, 948, 408, 125,  96, 671, 966,
        893, 719, 640, 629, 662, 998, 649, 735, 236, 489, 270, 399, 251,
        940, 189, 472, 451, 796, 504, 686, 233, 820, 773, 509, 698, 597,
        943, 547, 263, 752, 253, 733, 364, 430, 823, 112,  85, 129, 633,
         79, 836, 871, 435, 806, 951, 218, 176, 962]])

print(arr[0])

print(p[2])

[724 307 124 607  43 453 684 601 668  93 331 641 919 337 856 500 775 342
 976 655 812 775 979 985 769 458 142  22  26 591 528 265 391 750 693 978
 410  75 784 232 771 924 379 551  83 721  39 972 835 352 138 970  16 966
 194 884 738 995 858 689 352 820 809 971 340  53 640 348 280 417 443  71
 814 835 924 941 777 598 546 482 997 324 120 480 796 729 569 427 989 928
 810 476 795  35 355 142 623 619 960 844]
l


In [13]:
import numpy as np
arr1 = np.array([724,307,124,607,43,453,684,601,668,93,331,641,919,337,856,500,775,342,976,655,812,775,979,985,769,458,142,22,26,591,528,265,391,750,693,978,410,75,784,232,771,924,379,551,83,721,39,972,835,352,138,970,16,966,194,884,738,995,858,689,352,820,809,971,340,53,640,348,280,417,443,71,814,835,924,941,777,598,546,482,997,324,120,480,796,729,569,427,989,928,810,476,795,35,355,142,623,619,960,844])
arr2 = np.array([824,291,172,727,359,507,273,397,53,89,195,265,406,696,97,101,737,338,502,267,396,367,677,64,696,479,686,276,36,967,715,904,452,955,278,847,84,862,186,792,820,441,916,417,370,986,610,218,849,52,251,742,27,210,583,332,73,648,482,422,517,977,690,911,473,611,630,719,426,129,798,184,286,913,916,955,823,671,647,839,905,318,408,47,605,751,745,555,937,283,402,97,620,977,153,439,905,859,657,502])
arr3 = np.array([560,230,931,911,399,544,114,825,244,204,856,523,287,724,87,25,449,738,691,987,4,781,392,863,658,358,41,639,739,140,690,793,193,876,474,674,772,422,566,641,472,605,392,421,284,764,948,408,125,96,671,966,893,719,640,629,662,998,649,735,236,489,270,399,251,940,189,472,451,796,504,686,233,820,773,509,698,597,943,547,263,752,253,733,364,430,823,112,85,129,633,79,836,871,435,806,951,218,176,962])
matriz = np.array([[arr1],[arr2],[arr3]])
#print("Matriz:", matriz)
print("Transpuesta:", matriz.T)

Transpuesta: [[[724 824 560]]

 [[307 291 230]]

 [[124 172 931]]

 [[607 727 911]]

 [[ 43 359 399]]

 [[453 507 544]]

 [[684 273 114]]

 [[601 397 825]]

 [[668  53 244]]

 [[ 93  89 204]]

 [[331 195 856]]

 [[641 265 523]]

 [[919 406 287]]

 [[337 696 724]]

 [[856  97  87]]

 [[500 101  25]]

 [[775 737 449]]

 [[342 338 738]]

 [[976 502 691]]

 [[655 267 987]]

 [[812 396   4]]

 [[775 367 781]]

 [[979 677 392]]

 [[985  64 863]]

 [[769 696 658]]

 [[458 479 358]]

 [[142 686  41]]

 [[ 22 276 639]]

 [[ 26  36 739]]

 [[591 967 140]]

 [[528 715 690]]

 [[265 904 793]]

 [[391 452 193]]

 [[750 955 876]]

 [[693 278 474]]

 [[978 847 674]]

 [[410  84 772]]

 [[ 75 862 422]]

 [[784 186 566]]

 [[232 792 641]]

 [[771 820 472]]

 [[924 441 605]]

 [[379 916 392]]

 [[551 417 421]]

 [[ 83 370 284]]

 [[721 986 764]]

 [[ 39 610 948]]

 [[972 218 408]]

 [[835 849 125]]

 [[352  52  96]]

 [[138 251 671]]

 [[970 742 966]]

 [[ 16  27 893]]

 [[966 210 719]]

 [[194 583 640]

In [20]:
import numpy as np
matriz = np.array([[724,307,124,607,43,453,684,601,668,93,331,641,919,337,856,500,775,342,976,655,812,775,979,985,769,458,142,22,26,591,528,265,391,750,693,978,410,75,784,232,771,924,379,551,83,721,39,972,835,352,138,970,16,966,194,884,738,995,858,689,352,820,809,971,340,53,640,348,280,417,443,71,814,835,924,941,777,598,546,482,997,324,120,480,796,729,569,427,989,928,810,476,795,35,355,142,623,619,960,844],[824,291,172,727,359,507,273,397,53,89,195,265,406,696,97,101,737,338,502,267,396,367,677,64,696,479,686,276,36,967,715,904,452,955,278,847,84,862,186,792,820,441,916,417,370,986,610,218,849,52,251,742,27,210,583,332,73,648,482,422,517,977,690,911,473,611,630,719,426,129,798,184,286,913,916,955,823,671,647,839,905,318,408,47,605,751,745,555,937,283,402,97,620,977,153,439,905,859,657,502],[560,230,931,911,399,544,114,825,244,204,856,523,287,724,87,25,449,738,691,987,4,781,392,863,658,358,41,639,739,140,690,793,193,876,474,674,772,422,566,641,472,605,392,421,284,764,948,408,125,96,671,966,893,719,640,629,662,998,649,735,236,489,270,399,251,940,189,472,451,796,504,686,233,820,773,509,698,597,943,547,263,752,253,733,364,430,823,112,85,129,633,79,836,871,435,806,951,218,176,962]])

print("Diagonal principal:", np.diag(matriz))
print("Diagonal principal al reves:", np.fliplr(matriz).diagonal())

Diagonal principal: [724 291 931]
Diagonal principal al reves: [844 657 218]
